export const QuizData = [
  {
    question_id: 0,
    question: "Which one of these is the world's largest dam?",
    options: [
      {
        id: "option_1",
        answer: "	Tarbela Dam",
        status: false,
      },
      {
        id: "option_2",
        answer: "Fort Peck Dam",
        status: false,
      },
      {
        id: "option_3",
        answer: "Atatürk Dam",
        status: false,
      },
      {
        id: "option_4",
        answer: "The Three Gorges Dam",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["3"],
    answer_description: "The Three Gorges Dam",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 1,
    question: "What Do You Drink That Comes From A Cow?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Refermilk",
        status: false,
      },
      {
        id: "option_2",
        answer: "Qawsz",
        status: false,
      },
      {
        id: "option_3",
        answer: "Qazxsw",
        status: false,
      },
      {
        id: "option_4",
        answer: "Used",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "cow gives us milk",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 2,
    question: "How Many Vowels Are There In The English Alphabet (Algebra  E)",
    options: [
      {
        id: "option_1",
        answer: "5",
        status: false,
      },
      {
        id: "option_2",
        answer: "6",
        status: false,
      },
      {
        id: "option_3",
        answer: "23",
        status: false,
      },
      {
        id: "option_4",
        answer: "1",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "ENGLISH EXPLANATION",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 3,
    question: "What Animal Goes “Moo”?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Cow",
        status: false,
      },
      {
        id: "option_2",
        answer: "Goat",
        status: false,
      },
      {
        id: "option_3",
        answer: "Both",
        status: false,
      },
      {
        id: "option_4",
        answer: "None",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "cow says it",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 4,
    question: "Which Animal Is Known As The King Of The Jungle?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Lion",
        status: false,
      },
      {
        id: "option_2",
        answer: "Ased",
        status: false,
      },
      {
        id: "option_3",
        answer: "Usedwasderf",
        status: false,
      },
      {
        id: "option_4",
        answer: "Rfdfff",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "lion is the king of jungle",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 5,
    question: "2nd Question",
    options: [
      {
        id: "option_1",
        answer: "Efdfcd",
        status: false,
      },
      {
        id: "option_2",
        answer: "Efdeferf",
        status: false,
      },
      {
        id: "option_3",
        answer: "Feferfr",
        status: false,
      },
      {
        id: "option_4",
        answer: "Erfrefrgfvr",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_4"],
    answer_description: "",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 6,
    question: "Name The National Fruit Of India?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Apple",
        status: false,
      },
      {
        id: "option_2",
        answer: "Mango",
        status: false,
      },
      {
        id: "option_3",
        answer: "Both",
        status: false,
      },
      {
        id: "option_4",
        answer: "None",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_2"],
    answer_description: "MANGO IS OUR NATIONAL FRIUT",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 7,
    question: "What Is The National Song Of India?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Vande Mataram",
        status: false,
      },
      {
        id: "option_2",
        answer: "Ggthhy",
        status: false,
      },
      {
        id: "option_3",
        answer: "Edrftg",
        status: false,
      },
      {
        id: "option_4",
        answer: "Edrftgyhhyujh",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "this is our national song",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 8,
    question: "What Is Your Name",
    options: [
      {
        id: "option_1",
        answer: "Vikas",
        status: false,
      },
      {
        id: "option_2",
        answer: "Kkgd",
        status: false,
      },
      {
        id: "option_3",
        answer: "Viay",
        status: false,
      },
      {
        id: "option_4",
        answer: "Akash",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1", "option_3"],
    answer_description: "this is good togo",
    image: true,
    image_path:
      "https://learn-176832-ruby.b176832.stage.eastus.az.svc.builder.ai/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZFE9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--13f7c51840db5ea8edab3b318245c3335abd9d04/IMG-20220930-WA0019.jpg",
    answer_submit: [],
    multiple_choice: true,
    question_instruction: "<p>dagadgndakng</p>",
  },
  {
    question_id: 9,
    question: "What Is The National Anthem Of India?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Janaganamana",
        status: false,
      },
      {
        id: "option_2",
        answer: "None",
        status: false,
      },
      {
        id: "option_3",
        answer: "Both",
        status: false,
      },
      {
        id: "option_4",
        answer: "All",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "this is the national anthem",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 10,
    question: "Sample Question",
    options: [
      {
        id: "option_1",
        answer: "Fvfvbf",
        status: false,
      },
      {
        id: "option_2",
        answer: "Cdcdvc",
        status: false,
      },
      {
        id: "option_3",
        answer: "Cdcd",
        status: false,
      },
      {
        id: "option_4",
        answer: "Cvcd",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 11,
    question: "Name The National Animal Of India?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Tig",
        status: false,
      },
      {
        id: "option_2",
        answer: "Lion",
        status: false,
      },
      {
        id: "option_3",
        answer: "Wsed",
        status: false,
      },
      {
        id: "option_4",
        answer: "None",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_2"],
    answer_description: "LION IS KING OF JUNGLE",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 12,
    question: "How Many Fingers Do You Have In One Hand?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "2",
        status: false,
      },
      {
        id: "option_2",
        answer: "5",
        status: false,
      },
      {
        id: "option_3",
        answer: "2",
        status: false,
      },
      {
        id: "option_4",
        answer: "10",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_2"],
    answer_description: "WE HAVE 5 FINGERS",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 13,
    question: "New Question  Test",
    options: [
      {
        id: "option_1",
        answer: "All",
        status: false,
      },
      {
        id: "option_2",
        answer: "Suds",
        status: false,
      },
      {
        id: "option_3",
        answer: "No",
        status: false,
      },
      {
        id: "option_4",
        answer: "Vbvbb ",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "Correct explanation with question image",
    image: true,
    image_path:
      "https://learn-176832-ruby.b176832.stage.eastus.az.svc.builder.ai/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFFCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6854c2587f977e58d7d3a72aa278ca5e55288113/pexels-karolina-grabowska-5472919.jpg",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 14,
    question:
      " Can You Name A Word That Starts With The Letter “C”?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "C",
        status: false,
      },
      {
        id: "option_2",
        answer: "B",
        status: false,
      },
      {
        id: "option_3",
        answer: "Q",
        status: false,
      },
      {
        id: "option_4",
        answer: "A",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "c starts with",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 15,
    question: " Who Designed The National Flag Of India?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "P Ingali Venkayya",
        status: false,
      },
      {
        id: "option_2",
        answer: "A",
        status: false,
      },
      {
        id: "option_3",
        answer: "B",
        status: false,
      },
      {
        id: "option_4",
        answer: "C",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "he is the one",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 16,
    question: "Question 1",
    options: [
      {
        id: "option_1",
        answer: "Defderf",
        status: false,
      },
      {
        id: "option_2",
        answer: "Dosedxsxcdcd",
        status: false,
      },
      {
        id: "option_3",
        answer: "Dddccx",
        status: false,
      },
      {
        id: "option_4",
        answer: "Cdcd",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_4"],
    answer_description: "",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 17,
    question: "What Part Of Your Body Lets You See?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Eyes",
        status: false,
      },
      {
        id: "option_2",
        answer: "Ears",
        status: false,
      },
      {
        id: "option_3",
        answer: "Both",
        status: false,
      },
      {
        id: "option_4",
        answer: "None",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "eyesss",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 18,
    question: "Name The National Bird Of India?(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Bird",
        status: false,
      },
      {
        id: "option_2",
        answer: "Hen",
        status: false,
      },
      {
        id: "option_3",
        answer: "Peacock",
        status: false,
      },
      {
        id: "option_4",
        answer: "None",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_3"],
    answer_description: "explanation",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 19,
    question: "Name The National Flower Of India(Algebra E)",
    options: [
      {
        id: "option_1",
        answer: "Lotus",
        status: false,
      },
      {
        id: "option_2",
        answer: "Flower",
        status: false,
      },
      {
        id: "option_3",
        answer: "Both",
        status: false,
      },
      {
        id: "option_4",
        answer: "None",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_1"],
    answer_description: "lotus is the national flower",
    image: false,
    image_path: "",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
  },
  {
    question_id: 20,
    question: "What Is It?",
    options: [
      {
        id: "option_1",
        answer: "Red",
        status: false,
      },
      {
        id: "option_2",
        answer: "Blue",
        status: false,
      },
      {
        id: "option_3",
        answer: "Green",
        status: false,
      },
      {
        id: "option_4",
        answer: "White",
        status: false,
      },
    ],
    status: false,
    correct_answer: ["option_2"],
    answer_description: "",
    image: true,
    image_path:
      "https://learn-176832-ruby.b176832.stage.eastus.az.svc.builder.ai/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1FCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d2027edc00cee570ce12cbc8ded4e7f81b2c958/clement-fusil-Fpqx6GGXfXs-unsplash.jpg",
    answer_submit: [],
    multiple_choice: false,
    question_instruction: "",
    last: false,
  },
];